# This is a basic workflow to help you get started with Actions

name: hugo-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install hugo
        run: |
          sudo apt-get update
          sudo apt-get install -y hugo

      - name: Setup theme
        run: git submodule update --init --recursive

      - name: Run hugo
        run: hugo -t risotto

      - name: Upload public folder
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: ./public
          overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup GitHup Pages
        uses: actions/configure-pages@v5

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: public
          path: ./public

      - name: Get artifact size
        run: du -sh ./public

      - name: Deploy public folder to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: public
        

